---

- hosts: localhost

  tasks:

  - name: install docker

    become: true

    yum:

      name: docker

      state: latest

  - name: start service

    become: true

    service:

      name: docker

      state: started


  
